#!/usr/bin/env python3
import subprocess
import os
import tempfile
import shutil

remote_url = "https://github.com/juniorrojas/algovivo.git"
checkout = "sample-puppeteer-setup"

with tempfile.TemporaryDirectory() as tmp_dirname:
    e = subprocess.call([
        "git", "clone", remote_url,
        tmp_dirname
    ])
    if e != 0:
        raise RuntimeError("git clone failed")

    e = subprocess.call([
        "git",
        "--git-dir", os.path.join(tmp_dirname, ".git"),
        "--work-tree", tmp_dirname,
        "checkout", checkout
    ])
    if e != 0:
        raise RuntimeError("git checkout failed")

    root_src_dirname = os.path.join(tmp_dirname, "example-puppeteer-setup")

    shutil.copy(os.path.join(root_src_dirname, "main.js"), "main.js")
    shutil.copy(os.path.join(root_src_dirname, "package.json"), "package.json")

    for dirname in ["utils", "public"]:
        if os.path.exists(dirname):
            if os.path.isdir(dirname):
                shutil.rmtree(dirname)
            else:
                os.remove(dirname)
        shutil.copytree(os.path.join(root_src_dirname, dirname), dirname)