name: build-csrc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: juniorrojas/llvm-enzyme:latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          export LLVM_BIN_DIR=/usr/lib/llvm-11/bin
          export ENZYME=/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-11.so
          export BUILD_WASM=1
          ./build.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: algovivo.wasm
          path: build/algovivo.wasm
  build-dynamic-lib:
    runs-on: ubuntu-latest
    container:
      image: juniorrojas/llvm-enzyme:latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          export LLVM_BIN_DIR=/usr/lib/llvm-11/bin
          export ENZYME=/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-11.so
          export BUILD_WASM=0
          ./build.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: algovivo.so
          path: build/algovivo.so