name: build-wasm
on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get install llvm-11 clang-11 lld-11 ninja-build
          ls -l /usr/lib/llvm-11/bin
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: EnzymeAD/Enzyme
          path: Enzyme
      - run: ls -l
      - name: Build Enzyme
        run: |
          cd Enzyme/enzyme
          mkdir build
          cd build
          cmake -G Ninja .. -DLLVM_DIR=/usr/lib/llvm-11/
          ninja
      - name: Build WASM
        run: |
          export LLVM_BIN_DIR=/usr/lib/llvm-11/bin
          export ENZYME=./Enzyme/enzyme/build/Enzyme/LLVMEnzyme-11.so
          ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: algovivo.wasm
          path: build/algovivo.wasm