name: build-wasm
on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches:
      - master

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get install llvm-11
          ls -l /usr/lib/llvm-11
      - uses: actions/checkout@v3
        with:
          repository: EnzymeAD/Enzyme
      # - name: Checkout code
      #   uses: actions/checkout@v3