name: build-wasm
on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          sudo apt-get install llvm-11
          ls -l /usr/lib/llvm-11