name: demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: juniorrojas/llvm-enzyme:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build WASM
        run: |
          export LLVM_BIN_DIR=/usr/lib/llvm-11/bin
          export ENZYME=/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-11.so
          ./build.sh
      - name: Upload WASM
        uses: actions/upload-artifact@v4
        with:
          name: algovivo.wasm
          path: build/algovivo.wasm
  test-demo:
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download WASM build
        uses: actions/download-artifact@v4
        with:
          name: algovivo.wasm
          path: build/
      - name: Build lib
        run: |
          npm ci
          npm run build
      - name: Build demo
        run: |
          cd demo
          npm ci
          npm run build
      - name: Test demo
        run: |
          cd demo
          npm test
      - name: Upload demo screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: ./demo/test/screenshot.out.png
      - name: Upload lib build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build