name: render-trajectory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: juniorrojas/llvm-enzyme:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build WASM
        run: |
          export LLVM_BIN_DIR=/usr/lib/llvm-11/bin
          export ENZYME=/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-11.so
          ./build.sh
      - name: Upload WASM
        uses: actions/upload-artifact@v3
        with:
          name: algovivo.wasm
          path: build/algovivo.wasm
  generate-trajectory:
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download WASM build
        uses: actions/download-artifact@v3
        with:
          name: algovivo.wasm
          path: build/
      - name: Generate trajectory frames
        run: |
          npm ci
          npm run build
          node test/neural/generateTrajectory.js
  render-trajectory:
    runs-on: ubuntu-latest
    needs: generate-trajectory
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download WASM build
        uses: actions/download-artifact@v3
        with:
          name: algovivo.wasm
          path: build/
      - name: Generate trajectory frames
        run: |
          npm ci
          npm run build
          node test/neural/renderTrajectory.js
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
      - name: Make trajectory video
        run: |
          ffmpeg -framerate 30 -i test/neural/frames.out/%d.png -pix_fmt yuv420p video.out.mp4 -y
      - name: Upload trajectory video
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: video.out.mp4