name: render-trajectory
on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches:
      - master

jobs:
  render-trajectory:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
          node test/neural/renderTrajectory.js
          ffmpeg -framerate 30 -i test/neural/frames.out/%d.png -pix_fmt yuv420p video.out.mp4 -y
      - name: Upload video
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: video.out.mp4