name: test-demo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          npm ci
          npm test