name: test-demo
on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches:
      - master

jobs:
  test-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
          cd demo
          npm ci
          npm run build
          npm test
      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: ./demo/test/screenshot.out.png