name: test-codegen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pytest

      - name: Test
        run: |
          export PYTHONPATH=./codegen
          pytest -s ./codegen/test
